version: '3'
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: qweEWQ45%$
      MSSQL_PID: Developer
    ports:
      - "1433:1433"

#comando para correrlo en el droplet
#docker run -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=qweEWQ45%$' -e 'MSSQL_PID=Developer' -p 1433:1433 -d mcr.microsoft.com/mssql/server
